.github/workflows/coverage.yaml, .github/workflows/python-app.yml, README.md, pyproject.toml, requirements.txt, src/caustic/cosmology.py, src/caustic/lenses/kappa_grid.py, src/caustic/utils.py
Kappa Grid is updated with the following:
- dtype no longer enforced for frequency space kernels
- docstrings added
- fft changed to rfft since kernels are real valued
- enforced shapes for fft and ifft
This PR closes #35
=> Update Kappa Grid fft and dtype behavior

src/caustic/lenses/base.py, src/caustic/lenses/utils.py, src/caustic/packed.py, src/caustic/parametrized.py, src/caustic/simulator.py
Adds subclass of Parametrized which defines a simulator object. This defines a behaviour for the `__call__` method to handle parameter packing then pass to a user defined forward method.
=> Simulator class

caustic/lenses/base.py, test/test_sie.py
The Jacobian of the deflection angle can be used to construct critical curves and caustics. Since `caustic` is autodifferentiable, this is really easy!
=> base lens can now compute deflection angle jacobian

caustic/forward_raytrace.py, caustic/lenses/base.py, caustic/utils.py, test/test_base.py
Forward raytrace is now a class method for lenses. It's format is similar to raytrace, though it goes the other way. Also only a single point can be forward raytraced at a time due to the variable output shape.
=> Forward raytrace in base lens class

caustic/lenses/__init__.py, caustic/lenses/base.py, caustic/lenses/tnfw.py, test/test_tnfw.py, test/utils.py
Adding the TNFW lensing profile as described by Baltz et al. 2008 Equation A.3.
The convergence has been normalized by Sigma_crit. The deflection angles have been adjusted to the proper units. The potential is left in the un-reduced version from the source.
=> Add TNFW lens

caustic/lenses/pixelated_convergence.py, test/test_kappa_grid.py
No padding is actually illegal, need to have kernel at 2x image size. So now we pad by tiling the image to maintain the infinite periodic field feature.
=> Fix to pixelated FFT with no padding

caustic/lenses/nfw.py, caustic/lenses/tnfw.py, caustic/parametrized.py, test/test_batching.py, test/test_nfw.py, test/test_tnfw.py
It turns out that `torch.where` does not protect from nans in the off branch. The condition is applied by multiplication, something like:
`torch.where(x < 1, A, B)` is the same as `A * (x < 1) + B * (x >= 1)`
So nan's are somehow magically avoided in the forward pass when they probably shouldn't be, but in the backward pass there is no avoiding them.
So I made two versions of each offending function and the user can now select whether they want to batch, or get derivatives.
=> Fix nan gradients in NFW and TNFW

.github/workflows/coverage.yaml, .github/workflows/python-app.yml, caustic/cosmology.py, caustic/lenses/base.py, caustic/parameter.py, caustic/parametrized.py, requirements.txt, setup.py, test/test_cosmology.py, test/test_multiplane.py, test/test_parameter.py
- A minor bug fix in the `Parameter.__repr__` method.
- An important bug fix in `Cosmology.__init__` not sending private tensors `device`.
- An important bug fixed in the `@unpack` decorator not handling the unpacking correctly list or dict `params` passed as an argument or a keyword argument. This issue was found using the `Multiplane` lens, and an appropriate test was created using this object. This issue was missed in previous tests since most of them use the `Simulator` class. The `Simulator.__call__` method does not use the unpack decorator, rather it calls `Parametrized.pack` directly.
- Loosened the requirements file
=> Bug fixes 20231008

.github/CONTRIBUTING.md
The link to the Scientific Python guide changed
Addresses and resolves the conversation from PR https://github.com/Ciela-Institute/caustics/pull/106 and Conversation https://github.com/Ciela-Institute/caustics/pull/106#discussion_r1414430843
=> Update Scientific Python link

src/caustics/sims/lens_source.py, src/caustics/utils.py, tests/test_simulator.py
A gaussian quadrature integrator allows for pixel brightnesses to be more accurately determined with fewer evaluations than simple supersampling. See further information on Gaussian quadrature here: https://en.wikipedia.org/wiki/Gaussian_quadrature
=> Adding gaussian quadrature integrator

README.md
Update link for SSEC Project Badge to default to the main SSEC page.
=> docs: Add link to SSEC in badge

.readthedocs.yml
Add matplotlib import in the beginning to avoid creation of font cache during building of jupyter notebooks.
=> ci: Add matplotlib import in RTD pre_build

docs/source/tutorials/BasicIntroduction.ipynb, docs/source/tutorials/InvertLensEquation.ipynb, docs/source/tutorials/LensZoo.ipynb, docs/source/tutorials/MultiplaneDemo.ipynb, docs/source/tutorials/Playground.ipynb, docs/source/tutorials/Simulators.ipynb, docs/source/tutorials/VisualizeCaustics.ipynb
With the new import hierarchy, some links in the tutorials were broken. Now they link correctly.
=> docs: Update tutorials to call modules with new paths

.github/workflows/cd.yml
This merge together the PRs: https://github.com/Ciela-Institute/caustics/pull/133 and https://github.com/Ciela-Institute/caustics/pull/132 from dependabot, however this is based on current `dev`.
=> chore: Bump actions download and upload artifact to v4

.github/workflows/image_ci.yml
This PR adds a patch fix to the docker image build ending up having both `load` and `push` which is invalid for that action.
=> ci: Fix docker image build issue with it getting to both load and push

docs/source/examples/Example_ImageFit_LM.ipynb, docs/source/examples/Example_ImageFit_NUTS.ipynb, docs/source/intro.md, docs/source/tutorials/InterfaceIntroduction_oop.ipynb, docs/source/tutorials/InterfaceIntroduction_yaml.ipynb, docs/source/tutorials/example.yml, src/caustics/sims/lens_source.py, tests/models/test_mod_api.py, tests/test_simulator_runs.py
Moving the argument `quad_level` to the init of `LensSource`. I think this would also be a good PR to refactor the internals of `LensSource` since it has gotten to be quite nested. Let's use this to discuss how it should look.
=> refactor: move quad_level to init

src/caustics/__init__.py, src/caustics/light/__init__.py, src/caustics/light/light_stack.py, tests/test_light_stack.py
=> Added light stack module to combine multiple light models

src/caustics/lenses/base.py, tests/test_sie.py, tests/test_time_delay.py
Time delays are now tested for the SIE model for various source positions and SIE parameters. Time delays are computed from the base `ThinLens` class, so in principle this means all lenses should have correct time delays now. Still, might be good to go back and test a few other lens models. Also, should test multiplane time delay too. 
Note: bug found in time delay calculation and was corrected. Needed to use reduced deflection angle rather than physical.
=> tests: Time delay now tested for SIE

src/caustics/lenses/pixelated_convergence.py, src/caustics/lenses/pixelated_potential.py, src/caustics/light/pixelated.py, src/caustics/light/pixelated_time.py, tests/test_pixelated_time.py
Sometimes it is nice to have the pixelated model fixed and only change the scaling of the model. For example with a PSF image fitting a star. The scale factor could also be used for a diffusion model operating on images with different units, to keep everything in distribution if the main difference is only a global scaling.
=> feat: adding scale parameters to pixelated models

README.md, docs/source/install.rst
Added a warning to the docs and to the ReadME about using Python >=3.12 until we have testing set up for 3.12 (I will then update this warning to >=3.13).
=> Warn python version

.github/workflows/ci.yml, .pre-commit-config.yaml, README.md, docs/source/install.rst, pyproject.toml, requirements.txt
Added 3.12 to CI workflow, and I also relaxed the Numba upper version limit. 
More generally, I think that strict version requirements and version upper bounds are generally not best practice for the following reasons:
1. While such reqs aim to improve reproducibility, as a trade-off, they increase the likelihood of conflicts down the road, harming future package maintainers. 
2. Upgrading versions usually fixes bugs rather than introducing new ones. The major exception to this is API changes, but I believe it is the duty of maintainers to adapt to API changes as they occur and set upper version limits as a last resort. 
3. Caustics is less a top-level package, and more of a strong lensing framework which can be built upon by others. Since pinning versions is best done at the top level …
=> Upgrade to compatibility with Python 3.12
